version: '3'

services:

  bind:
    build: ./bind/
    image: tsutomu/bind
    container_name: bind
    ports:
      - ${IP_FOR_BIND}:53:53/udp
      - ${IP_FOR_BIND}:53:53/tcp
    volumes:
      - ./bind/conf/named.conf.local:/etc/bind/named.conf.local:ro
      - ./bind/conf/named.conf.options:/etc/bind/named.conf.options:ro
      - ./bind/conf/example.com:/etc/bind/example.com:ro
      - ./bind/conf/0.5.10.in-addr.arpa:/etc/bind/0.5.10.in-addr.arpa:ro

  drone-server:
    image: drone/drone:0.7
    container_name: drone-server
    ports:
      - ${IP_FOR_DRONE}:80:8000
    volumes:
      - ./drone:/var/lib/drone/
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITLAB=true
      - DRONE_GITLAB_CLIENT=${DRONE_GITLAB_CLIENT}
      - DRONE_GITLAB_SECRET=${DRONE_GITLAB_SECRET}
      - DRONE_GITLAB_URL=${DRONE_GITLAB_URL}
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/drone:0.7
    container_name: drone-agent
    command: agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}

  gitlab:
    image: gitlab/gitlab-ce:9.3.2-ce.0
    container_name: gitlab
    hostname: gitlab.example.com
    ports:
      - ${IP_FOR_GITLAB}:80:80
    volumes:
      - ./gitlabfs/config:/etc/gitlab
      - ./gitlabfs/data:/var/opt/gitlab
    environment:
      - GITLAB_OMNIBUS_CONFIG="external_url 'http://gitlab.example.com/'; gitlab_rails['lfs_enabled'] = true;"

